key_settings: Delete
esp_mode: AlwaysOn
esp_toogle: null
esp_settings:
  player.enemy:
    type: Player
    box_type: Box2D
    box_color:
      type: Static
      options:
        value: 3221191936
    box_width: 1.0
    skeleton: true
    skeleton_color:
      type: Static
      options:
        value: 3204448511
    skeleton_width: 1.0
    health_bar: Left
    health_bar_width: 10.0
    tracer_lines: None
    tracer_lines_color:
      type: Static
      options:
        value: 4294967295
    tracer_lines_width: 1.0
    info_name: true
    info_name_color:
      type: Static
      options:
        value: 3204448511
    info_distance: false
    info_distance_color:
      type: Static
      options:
        value: 3204448511
    near_players: false
    near_players_distance: 20.0
    info_weapon: false
    info_weapon_color:
      type: Static
      options:
        value: 3204448511
    info_hp_text: false
    info_hp_text_color:
      type: Static
      options:
        value: 4278253055
    info_flag_kit: false
    info_flag_flashed: false
    info_flags_color:
      type: Static
      options:
        value: 3204448511
    head_dot: NotFilled
    head_dot_color:
      type: Static
      options:
        value: 3204448511
    head_dot_thickness: 1.0
    head_dot_base_radius: 2.0
    head_dot_z: 1.0
esp_settings_enabled:
  player.enemy: true
bomb_timer: true
spectators_list: false
valthrun_watermark: true
mouse_x_360: 16364
trigger_bot_mode: AlwaysOn
key_trigger_bot: MouseLeft
trigger_bot_team_check: true
trigger_bot_delay_min: 0
trigger_bot_delay_max: 0
trigger_bot_shot_duration: 14
trigger_bot_check_target_after_delay: false
aim_assist_recoil: true
aim_assist_recoil_min_bullets: 1
hide_overlay_from_screen_capture: true
render_debug_window: false
metrics: true
web_radar_url: null
web_radar_advanced_settings: false
grenade_helperactive: true
grenade_helperui_sort_order: Alphabetical
grenade_helpercircle_distance: 150.0
grenade_helpercircle_radius: 20.0
grenade_helpercircle_segments: 32
grenade_helperangle_threshold_yaw: 0.1
grenade_helperangle_threshold_pitch: 0.5
grenade_helpercolor_position: 4294967295
grenade_helpercolor_position_active: 4278255360
grenade_helpercolor_angle: 4278190335
grenade_helpercolor_angle_active: 4278255360
grenade_helpermap_spots: {}
grenade_helpergrenade_background: true
imgui: |+
  [Window][Debug##Default]
  Pos=60,60
  Size=400,400
  Collapsed=0

  [Window][overlay]
  Pos=0,0
  Size=1280,719
  Collapsed=0

  [Window][Valthrun]
  Pos=198,196
  Size=650,300
  Collapsed=0

  [Window][Trigger bot key]
  Pos=537,342
  Size=206,34
  Collapsed=0

  [Window][Toggle Settings]
  Pos=537,342
  Size=206,34
  Collapsed=0

